---
# Documentation
# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
-   package-ecosystem: github-actions
    directory: /
    schedule:
        interval: quarterly
    labels:
    -   Dependencies
    -   Infrastructure
    groups:
        actions-infrastructure:
            patterns:
            -   actions/*

-   package-ecosystem: npm
    directory: /
    schedule:
        interval: quarterly
    groups:
        npm:
            patterns:
            -   '*'
