---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
    autoupdate_commit_msg: 'chore: update pre-commit hooks'
    autoupdate_schedule: quarterly
    autofix_commit_msg: 'style: pre-commit fixes'
    autofix_prs: false

#  Files that should not be checked
exclude: |
    (?x)^(
        nilearn/datasets/tests/data/localizer_behavioural.tsv
        | nilearn/_version.py
        | asv_benchmarks/asv.conf.json
        | asv_benchmarks/results
        | asv_benchmarks/nilearn
        | asv_benchmarks/env
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

    # Checks for .rst files
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

    # Checks for spelling errors
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    -   id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies: [tomli]

    # Format YAML files
-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']

    # Format TOML files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']

    # Check formatting of CSS
    # prettier: https://prettier.io/
-   repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.4
    hooks:
    -   id: prettier
        types_or: [css]

-   repo: https://github.com/djlint/djLint
    rev: v1.40.3
    hooks:
    -   id: djlint
    -   id: djlint-reformat
    -   id: djlint-jinja
    -   id: djlint-reformat-jinja
        exclude: |
            (?x)^(
                doc/ci.jinja
            )$

-   repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v5.1.0
    hooks:
    -   id: complexipy
        args: [--max-complexity-allowed=75]

    # Lint and format Python code
