---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
    autoupdate_commit_msg: 'chore: update pre-commit hooks'
    autoupdate_schedule: quarterly
    autofix_commit_msg: 'style: pre-commit fixes'
    autofix_prs: false

#  Files that should not be checked
exclude: |
    (?x)^(
        nilearn/datasets/tests/data/localizer_behavioural.tsv
        | nilearn/plotting/data/js/.*js
        | nilearn/_version.py
        | asv_benchmarks/asv.conf.json
        | asv_benchmarks/results
        | asv_benchmarks/nilearn
        | asv_benchmarks/env
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

    # Checks for .rst files
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

    # Checks for spelling errors
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    -   id: codespell
        args: [--toml, pyproject.toml]
        additional_dependencies: [tomli]

    # Format YAML files
-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']

    # Format TOML files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']

    # Check formatting of CSS
    # prettier: https://prettier.io/
-   repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
    -   id: prettier
        types_or: [css]

-   repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
    -   id: djlint
    -   id: djlint-reformat
    -   id: djlint-jinja
    -   id: djlint-reformat-jinja
        exclude: |
            (?x)^(
                doc/ci.jinja
            )$

    # Lint and format Python code
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    -   id: ruff-check
        # args: [--statistics]
        args: [--fix, --show-fixes, --unsafe-fixes]
    -   id: ruff-format
        # args: [--diff]
    -   id: ruff-check
        # additional check to keep tests short
        args: [--config, lint.pylint.max-statements=32]
        files: |
            (?x)^(
                nilearn/.*/test_.*py
            )$

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0    # replace with latest tag on GitHub
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        -   black
        # ignoring certain files
        # to avoid generating lines that are too long
        # or do not comply with some of the requirements
        # of other linting / formaating tools (doc8, ruff...)
        exclude: |
            (?x)^(
                doc/building_blocks/gpu_usage.rst
                | nilearn/_utils/param_validation.py
            )$

-   repo: https://github.com/standard/standard
    rev: v17.1.2
    hooks:
    -   id: standard
        files: tests/js/.*js

    # Check imports contracts
-   repo: https://github.com/seddonym/import-linter
    rev: v2.11
    hooks:
    -   id: import-linter
        args: [--verbose]
        language: python

-   repo: https://github.com/PyCQA/doc8
    rev: v2.0.0
    hooks:
    -   id: doc8
        args: [--config=pyproject.toml, nilearn]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
    -   id: mypy
        files: nilearn
        additional_dependencies: [numpy, nibabel, requests, pandas-stubs, lxml-stubs, types-requests]
        args: [--config-file, pyproject.toml, --pretty]
