---
# 📚 For a complete reference to this file, see the documentation at
# https://docs.sourcery.ai/Configuration/Project-Settings/

version: '1' # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
-   .env
-   .git
-   .venv
-   .tox
-   dist
-   doc/auto_examples
-   doc/_build
-   env
-   node_modules
-   vendor
-   venv
-   nilearn/_version.py
-   nilearn/externals/
-   nilearn/plotting/data/js/

rule_settings:
    enable:
    -   default
    disable:
    -   reintroduce-else
    -   merge-else-if
    -   merge-nested-ifs
    -   introduce-default-else
    -   boolean-if-exp-identity
    -   swap-if-else-branches
    -   switch
    -   dict-comprehension
    -   use-or-for-fallback
    -   dont-reassign-caught-exceptions
    -   use-getitem-for-re-match-groups
    -   merge-comparisons
    -   remove-pass-elif
    -   remove-redundant-if
    -   yield-from
    # not auto fixable
    -   avoid-builtin-shadow
    -   low-code-quality
    -   raise-specific-error
    # ignore
    -   inline-variable
    # ignore walrus
    -   use-named-expression
    # do not user '|' for dict update
    -   dict-assign-update-to-union
    # ignore in tests
    -   no-loop-in-tests
    -   no-conditionals-in-tests
    # done
    -   raise-from-previous-error
    -   remove-empty-nested-block
    -   merge-duplicate-blocks
    -   lift-return-into-if
    -   last-if-guard
    rule_types:
    -   refactoring
    -   suggestion
    -   comment
    python_version: '3.9'

metrics:
    quality_threshold: 10.0
