---
# 📚 For a complete reference to this file, see the documentation at
# https://docs.sourcery.ai/Configuration/Project-Settings/


version: '1'  # The schema version of this config file

ignore: # A list of paths or files which Sourcery will ignore.
-   nilearn/_version.py
-   externals/
-   nilearn/externals/tempita/
-   nilearn/externals/tempita/__init__.py
-   plotting/data/js/*.js

rule_settings:
    enable:
    -   default
    disable:
    -   no-loop-in-tests
    -   no-conditionals-in-tests
    -   low-code-quality
    # --------------------
    -   raise-from-previous-error   # │    21 │
    -   use-named-expression        # │    16 │
    -   avoid-builtin-shadow        # │     9 │
    # -   remove-redundant-if         # │     7 │
    -   assign-if-exp               # │     5 │
    # -   reintroduce-else            # │     5 │
    -   dict-assign-update-to-union # │     4 │
    # -   swap-if-else-branches       # │     4 │
    -   use-or-for-fallback         # │     4 │
    -   raise-specific-error        # │     3 │
    # -   introduce-default-else      # │     2 │
    # -   merge-duplicate-blocks      # │     2 │
    # -   merge-else-if-into-elif     # │     2 │
    # -   remove-unnecessary-else     # │     2 │
    -   switch                      # │     1 │

    rule_types:
    -   refactoring
    # -   suggestion
    # -   comment
    python_version: '3.9'

metrics:
    quality_threshold: 25.0
