---
# similar to scikit-learn .codecov.yml
coverage:
    status:
        project:
            default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 1%:
                target: auto
                threshold: 1%

ignore:
-   '*externals/.*'  # ignore folders and all its contents
