---
# similar to scikit-learn .codecov.yml
# https://docs.codecov.com/docs/codecovyml-reference
coverage:
    status:
        # Commits should not make the overall
        # project coverage decrease by more than 1%:
        project:
            default:
                target: auto
                threshold: 1%
        # OFF on PR
        patch: off

github_checks:
    annotations: false
