"""Generate HTML reports."""

import abc
import uuid
import warnings
from copy import deepcopy
from datetime import datetime
from string import Template
from typing import Any, ClassVar

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape

from nilearn._utils.helpers import is_matplotlib_installed
from nilearn._utils.html_document import HTMLDocument
from nilearn._utils.logger import find_stack_level
from nilearn._utils.versions import SKLEARN_GTE_1_7
from nilearn._version import __version__
from nilearn.reporting._utils import (
    dataframe_to_html,
    model_attributes_to_dataframe,
)
from nilearn.reporting.utils import (
    CSS_PATH,
    TEMPLATE_ROOT_PATH,
    figure_to_svg_base64,
)

UNFITTED_MSG = (
    "\nThis estimator has not been fit yet.\n"
    "Make sure to run `fit` before inspecting reports."
)

MISSING_ENGINE_MSG = (
    "\nNo plotting back-end detected.\nReport will be missing figures."
)


class ReportMixin:
    """A mixin class to be used with classes that require reporting
    functionality.

    ReportMixin uses one public attribute of type bool:

    reports: The value to indicate if reporting is enabled.

    ReportMixin uses two private attributes of type dict:

    _report_content : The content to enrich the report. Some fields can be
    initialized in estimator constructor. Others can be added after model fit.
    Possible generic keys are:
        - title : title to be used for the report
        - description : description of the report generated by the estimator
        - summary : summary
        - warning_message : possible warning message
    _report_data : Contains data from model fit. If reporting is disabled, or
    the model is not fit, this attribute does not exist.

    Classes inheriting from ReportMixin should implement ``_get_displays``
    to return the displays to be embedded to the report.
    """

    _REPORT_DEFAULTS: ClassVar[dict[str, Any]] = {
        "title": None,
        "description": "",
        "summary": {},
        "warning_messages": [],
        "engine": "matplotlib",
        "has_plotting_engine": True,
    }

    # report body template name for the estimator
    _template_name = ""

    def __init_subclass__(cls):
        super().__init_subclass__()
        # sets implementing class _REPORT_DEFAULTS
        # updating the base class value with implementing class value
        cls._REPORT_DEFAULTS = cls._update_defaults(
            ReportMixin._REPORT_DEFAULTS, cls._REPORT_DEFAULTS
        )

    @classmethod
    def _update_defaults(cls, base_dict: dict, update_dict: dict):
        """Return a new dictionary with the values of dictionary base_dict
        updated recursively with the values of update_dict.
        """
        new_dict = deepcopy(base_dict)
        for k, v in update_dict.items():
            if (
                k in new_dict
                and isinstance(new_dict[k], dict)
                and isinstance(v, dict)
            ):
                v = cls._update_defaults(new_dict[k], v)
            new_dict[k] = v
        return new_dict

    def _reset_report(self):
        self._report_content = deepcopy(self._REPORT_DEFAULTS)
        self._report_info = {}

        if self._has_report_data():
            del self._reporting_data

    def _has_report_data(self):
        """
        Check if the model is fitted and _reporting_data is populated.

        Returns
        -------
        bool
            True if reporting is enabled, the model is fitted and
        _reporting_data is populated; False otherwise.
        """
        return hasattr(self, "_reporting_data")

    def _append_warning(self, warning: str):
        """Append the specified warning to the warning list of the report.

        Parameters
        ----------
        warning: str
            warning to be added to the list of warnings.
        """
        self._report_content["warning_messages"].append(warning)

    def _get_warnings(self):
        """Return the sorted list of report warnings.

        Returns
        -------
        list of str
            the list of warnings, empty list if there are no warnings
        """
        return sorted(set(self._report_content["warning_messages"]))

    def _display_report_warnings(self):
        report_warnings = self._get_warnings()
        if report_warnings:
            for msg in report_warnings:
                warnings.warn(
                    msg,
                    stacklevel=find_stack_level(),
                    category=UserWarning,
                )

    def _dataframe_to_html(
        self,
        df_cvrt,
        precision: int = 2,
        header: bool = True,
        index: bool = False,
        sparsify: bool = False,
    ):
        """Create html content from the specified dataframe content."""
        return dataframe_to_html(
            df_cvrt,
            precision=precision,
            header=header,
            index=index,
            sparsify=sparsify,
        )

    def _dict_to_html(
        self,
        dict_cvrt,
        precision: int = 2,
        header: bool = True,
        index: bool = False,
        sparsify: bool = False,
    ):
        """Create html content from the specified dictionary content. The
        dictionary is expected to be key value pairs without depth.
        """
        df_cvrt = pd.DataFrame.from_dict(dict_cvrt)
        return self._dataframe_to_html(
            df_cvrt,
            precision=precision,
            header=header,
            index=index,
            sparsify=sparsify,
        )

    def _model_params_to_html(self):
        """List model attributes and values in html."""
        if SKLEARN_GTE_1_7:
            parameters = self._repr_html_()
        else:
            # TODO (sklearn > 1.6.2) remove else block
            parameters = model_attributes_to_dataframe(self)
            with pd.option_context("display.max_colwidth", 100):
                parameters = dataframe_to_html(
                    parameters,
                    precision=2,
                    header=True,
                    sparsify=False,
                )
        return parameters

    def _get_body_template(self, estimator_type: str):
        """Return body template for this estimator depending on the specified
        `estimator_type` and `_template_name` attributes.
        """
        env = return_jinja_env()

        body_tpl_path = f"html/{estimator_type}/{self._template_name}"
        return env.get_template(body_tpl_path)

    def _get_partial_template(
        self, estimator_type: str, tpl_name: str, is_common: bool = False
    ):
        """Return a partial template for the specified `_estimator_type`.
        If `is_common=True`, the template is not searched in estimator's
        template directory but common `partials` directory.
        """
        env = return_jinja_env()
        loc = f"/{estimator_type}" if not is_common else ""
        return env.get_template(f"html{loc}/partials/{tpl_name}.jinja")

    def _run_report_checks(self):
        """Run standard checks before report is generated.

        Checks if:
        - reporting is enabled
        - model is fitted
        - reporting was enabled at the time of fit
        - matplotlib is installed
        """
        if self.reports is False:
            self._append_warning(
                "\nReport generation not enabled!\nNo visual outputs created."
            )

        if not self.__sklearn_is_fitted__():
            self._append_warning(UNFITTED_MSG)

        report = self._report_content
        if self.__sklearn_is_fitted__() and not report["reports_at_fit_time"]:
            self._append_warning(
                "\nReport generation was disabled when fit was run. "
                "No reporting data is available.\n"
                "Make sure to set self.reports=True before fit."
            )

        if not is_matplotlib_installed():
            self._append_warning(MISSING_ENGINE_MSG)

    def _set_report_basics(self, title: str | None = None):
        """Populate `_report_content` and `report_info` fields with values that
        will be used in report body template.

        The fields are:
        - unique_id
        - title
        - has_plotting_engine
        - docstring
        - parameters
        - date
        - version

        TODO
        ----
        _report_content could be used instead of _report_info. However after
        report_generation _report_info is reset to {}. If _report_content can
        safely be reset after report generation, _report_info can be removed.
        """
        report_content = self._report_content
        # Generate a unique ID for report
        report_content["unique_id"] = str(uuid.uuid4()).replace("-", "")

        # Set title for report
        report_content["title"] = title or self.__class__.__name__

        report_content["has_plotting_engine"] = is_matplotlib_installed()

        report_info = self._report_info

        # TODO clean up docstring from RST formatting
        if self.__doc__ is not None:
            report_info["docstring"] = self.__doc__.split("Parameters\n")[0]
        else:
            report_info["docstring"] = ""

        report_info["parameters"] = self._model_params_to_html()

        report_info["date"] = datetime.now().replace(microsecond=0).isoformat()

        report_info["version"] = __version__

    def generate_report(self, title: str | None = None):
        """Generate an HTML report for this estimator.

        Parameters
        ----------
        title : :obj:`str` or None, default=None
            title for the report. If None, title will be the class name.

        Returns
        -------
        report : `nilearn.reporting.html_report.HTMLReport`
            HTML report for the masker.
        """
        self._run_report_checks()
        self._set_report_basics(title)

        self._display_report_warnings()

        return _create_report(self, self._report_content)

    @abc.abstractmethod
    def _reporting(self):
        raise NotImplementedError()


class HTMLReport(HTMLDocument):
    """A report written as HTML.

    Methods such as ``save_as_html``, or ``open_in_browser``
    are inherited from class ``nilearn.plotting.html_document.HTMLDocument``.

    Parameters
    ----------
    head_tpl : str.Template or Jinja Template
        This is meant for display as a full page, like writing on disk.
        This is the Template object used to generate the HTML head
        section of the report. The template should be filled with:

            - title: The title of the HTML page.
            - body: The full body of the HTML page. Provided through
                the ``body`` input.

    body : :obj:`str`
        This parameter is used for embedding in the provided
        ``head_tpl`` template. It contains the full body of the
        HTML page.

    head_values : :obj:`dict`, default=None
        Additional substitutions in ``head_tpl``.
        if ``None`` is passed, defaults to ``{}``

        .. note::
            This can be used to provide additional values
            with custom templates.

    """

    def __init__(self, head_tpl, body, head_values=None):
        """Construct the ``HTMLReport`` class."""
        if head_values is None:
            head_values = {}

        if isinstance(head_tpl, Template):
            html = head_tpl.safe_substitute(body=body, **head_values)
            self.head_tpl = head_tpl.safe_substitute(**head_values)
        else:
            # in this case we are working with jinja template
            html = head_tpl.render(body=body, **head_values)
            self.head_tpl = head_tpl.render(**head_values)

        self.body = body

        super().__init__(html)

    def _repr_html_(self):
        """Return body of the report.

        Method used by the Jupyter notebook.
        Users normally won't call this method explicitly.
        """
        return self.body

    def __str__(self):
        return self.body


def return_jinja_env() -> Environment:
    """Set up the jinja Environment."""
    return Environment(
        loader=FileSystemLoader(TEMPLATE_ROOT_PATH),
        autoescape=select_autoescape(),
        lstrip_blocks=True,
        trim_blocks=True,
    )


def embed_img(display):
    """Embed an image or just return its instance if already embedded.

    Parameters
    ----------
    display : obj
        A Nilearn plotting object to display.

    Returns
    -------
    embed : str
        Binary image string.

    """
    if display is None:  # no image to display
        return None
    # If already embedded, simply return as is
    if isinstance(display, str):
        return display
    return figure_to_svg_base64(display.frame_axes.figure)


def assemble_report(body: str, title: str) -> HTMLReport:
    """Put together head and body of report."""
    env = return_jinja_env()

    head_tpl = env.get_template("html/head.jinja")

    head_css_file_path = CSS_PATH / "head.css"
    with head_css_file_path.open(encoding="utf-8") as head_css_file:
        head_css = head_css_file.read()

    return HTMLReport(
        body=body,
        head_tpl=head_tpl,
        head_values={
            "head_css": head_css,
            "version": __version__,
            "page_title": title,
            "display_footer": "style='display: none'" if is_notebook() else "",
        },
    )


def _insert_figure_partial(
    estimator, engine, content, displayed_maps, unique_id: str
) -> str:
    tpl = estimator._get_partial_template(
        estimator._estimator_type, "figure.jinja", False
    )

    if not isinstance(content, list):
        content = [content]
    return tpl.render(
        engine=engine,
        content=content,
        displayed_maps=displayed_maps,
        unique_id=unique_id,
    )


def _create_report(
    estimator,
    data: dict[str, Any],
) -> HTMLReport:
    embeded_images = None
    image = estimator._reporting()
    if image is None:
        embeded_images = None
    elif not isinstance(image, list):
        embeded_images = embed_img(image)
    elif all(x is None for x in image):
        embeded_images = None
    else:
        embeded_images = [embed_img(i) for i in image]

    summary_html: None | dict | str = None
    # only convert summary to html table if summary exists
    if "summary" in data and data["summary"] is not None:
        # convert region summary to html table
        # for Surface maskers create a table for each part
        if "Surface" in estimator.__class__.__name__:
            summary_html = {}
            for part in data["summary"]:
                summary_html[part] = pd.DataFrame.from_dict(
                    data["summary"][part]
                )
                summary_html[part] = dataframe_to_html(
                    summary_html[part],
                    precision=2,
                    header=True,
                    index=False,
                    sparsify=False,
                )
        # otherwise we just have one table
        elif "Nifti" in estimator.__class__.__name__:
            summary_html = dataframe_to_html(
                pd.DataFrame.from_dict(data["summary"]),
                precision=2,
                header=True,
                index=False,
                sparsify=False,
            )

    if "n_elements" not in data:
        data["n_elements"] = 0

    if "coverage" not in data:
        data["coverage"] = ""
    if not isinstance(data["coverage"], str):
        data["coverage"] = f"{data['coverage']:0.1f}"

    if "overlay" in data:
        data["overlay"] = embed_img(data["overlay"])

    docstring = estimator._report_info["docstring"]
    parameters = estimator._report_info["parameters"]

    body_tpl = estimator._get_body_template(estimator._estimator_type)

    body = body_tpl.render(
        content=embeded_images,
        docstring=docstring,
        parameters=parameters,
        figure=(
            _insert_figure_partial(
                estimator,
                data["engine"],
                embeded_images,
                data["displayed_maps"],
                data["unique_id"],
            )
            if "engine" in data
            else None
        ),
        summary_html=summary_html,
        is_notebook=is_notebook(),
        **data,
    )

    return assemble_report(body, f"{data['title']} report")


def is_notebook() -> bool:
    """Detect if we are running in a notebook.

    Adapted from https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook
    """
    try:
        shell = get_ipython().__class__.__name__  # type: ignore[name-defined]
    except NameError:
        shell = False

    try:
        import marimo as mo

        is_marimo = mo.running_in_notebook()
    except ImportError:
        is_marimo = False

    if shell:
        if shell == "ZMQInteractiveShell":
            return True  # Jupyter notebook or qtconsole
        elif shell == "TerminalInteractiveShell":
            return False  # Terminal running IPython
        else:
            return False  # Other type (?)

    if is_marimo:
        return is_marimo

    return False
