"""Define ReportMixin to be extended by the classes that require reporting
functionality.
"""

import uuid
import warnings
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Any, ClassVar

import pandas as pd

from nilearn._utils.helpers import is_matplotlib_installed
from nilearn._utils.logger import find_stack_level
from nilearn._utils.versions import SKLEARN_GTE_1_7
from nilearn._version import __version__
from nilearn.reporting._utils import (
    dataframe_to_html,
    model_attributes_to_dataframe,
)
from nilearn.reporting.html_report import (
    MISSING_ENGINE_MSG,
    UNFITTED_MSG,
    HTMLReport,
    assemble_report,
    return_jinja_env,
)
from nilearn.reporting.utils import (
    figure_to_svg_base64,
)

OTHER_JS = Path(__file__).parents[1] / "plotting" / "data" / "js"


class ReportMixin:
    """A mixin class to be used with classes that require reporting
    functionality. It provides generic methods for report generation.

    ReportMixin uses one public attribute of type bool:

    reports: The value to indicate if reporting is enabled.

    ReportMixin uses two private attributes of type dict:

    _report_content : The content to enrich the report. Some fields can be
    initialized in estimator constructor. Others can be added after model fit.
    Possible generic keys are:
        - title : title to be used for the report
        - description : description of the report generated by the estimator
        - summary : summary
        - warning_messages : possible warning message
    _report_data : Contains data from model fit. If reporting is disabled, or
    the model is not fit, this attribute does not exist.

    Classes inheriting from ReportMixin should implement ``generate_report``
    method.
    """

    _REPORT_DEFAULTS: ClassVar[dict[str, Any]] = {
        "title": None,
        "description": "",
        "summary": {},
        "warning_messages": [],
        "engine": "matplotlib",
        "has_plotting_engine": True,
    }

    # report body template name for the estimator
    _template_name = ""

    def __init_subclass__(cls):
        super().__init_subclass__()
        # sets implementing class _REPORT_DEFAULTS
        # updating the base class value with implementing class value
        cls._REPORT_DEFAULTS = cls._update_defaults(
            ReportMixin._REPORT_DEFAULTS, cls._REPORT_DEFAULTS
        )

    @classmethod
    def _update_defaults(cls, base_dict: dict, update_dict: dict):
        """Return a new dictionary with the values of dictionary base_dict
        updated recursively with the values of update_dict.
        """
        new_dict = deepcopy(base_dict)
        for k, v in update_dict.items():
            if (
                k in new_dict
                and isinstance(new_dict[k], dict)
                and isinstance(v, dict)
            ):
                v = cls._update_defaults(new_dict[k], v)
            new_dict[k] = v
        return new_dict

    def _reset_report(self):
        self._report_content = deepcopy(self._REPORT_DEFAULTS)

        if self._has_report_data():
            del self._reporting_data

    def _has_report_data(self):
        """
        Check if the model is fitted and _reporting_data is populated.

        Returns
        -------
        bool
            True if reporting is enabled, the model is fitted and
        _reporting_data is populated; False otherwise.
        """
        return hasattr(self, "_reporting_data")

    def _append_report_warning(self, warning: str):
        """Append the specified warning to the warning list of the report.

        Parameters
        ----------
        warning: str
            warning to be added to the list of warnings.
        """
        self._report_content["warning_messages"].append(warning)

    def _get_report_warnings(self):
        """Return the sorted list of report warnings.

        Returns
        -------
        list of str
            the list of warnings, empty list if there are no warnings
        """
        return sorted(set(self._report_content["warning_messages"]))

    def _reset_report_warnings(self):
        self._report_content["warning_messages"] = []

    def _display_report_warnings(self):
        report_warnings = self._get_report_warnings()

        if report_warnings:
            for msg in report_warnings:
                warnings.warn(
                    msg,
                    stacklevel=find_stack_level(),
                    category=UserWarning,
                )

    def _set_report_basics(self, **kwargs):
        """Populate `_report_content` with values that will be used in report
        body template.

        The fields are:
        - unique_id
        - title
        - engine
        - has_plotting_engine
        - docstring
        - parameters
        - date
        - version
        """
        report_content = self._report_content
        # Generate a unique ID for report
        report_content["unique_id"] = str(uuid.uuid4()).replace("-", "")

        # Set title for report
        report_content["title"] = kwargs.get("title", self.__class__.__name__)

        report_content["engine"] = kwargs.get("engine", "matplotlib")

        report_content["has_plotting_engine"] = is_matplotlib_installed()

        # TODO clean up docstring from RST formatting
        if self.__doc__ is not None:
            report_content["docstring"] = self.__doc__.split("Parameters\n")[0]
        else:
            report_content["docstring"] = ""

        report_content["parameters"] = self._model_params_to_html()

        report_content["date"] = (
            datetime.now().replace(microsecond=0).isoformat()
        )

        report_content["version"] = __version__

    def _run_report_checks(self, **kwargs):
        """Run standard checks before report is generated.

        Checks if:
        - reporting is enabled
        - model is fitted
        - reporting was enabled at the time of fit
        - matplotlib is installed
        """
        _ = kwargs
        if self.reports is False:
            self._append_report_warning(
                "\nReport generation not enabled!\nNo visual outputs created."
            )

        if not self.__sklearn_is_fitted__():
            self._append_report_warning(UNFITTED_MSG)

        report = self._report_content
        if self.__sklearn_is_fitted__() and not report["reports_at_fit_time"]:
            self._append_report_warning(
                "\nReport generation was disabled when fit was run. "
                "No reporting data is available.\n"
                "Make sure to set self.reports=True before fit."
            )

        if not is_matplotlib_installed():
            self._append_report_warning(MISSING_ENGINE_MSG)

    def _dataframe_to_html(
        self,
        df_cvrt,
        precision: int = 2,
        header: bool = True,
        index: bool = False,
        sparsify: bool = False,
    ):
        """Create html content from the specified dataframe content."""
        return dataframe_to_html(
            df_cvrt,
            precision=precision,
            header=header,
            index=index,
            sparsify=sparsify,
        )

    def _dict_to_html(
        self,
        dict_cvrt,
        precision: int = 2,
        header: bool = True,
        index: bool = False,
        sparsify: bool = False,
    ):
        """Create html content from the specified dictionary content. The
        dictionary is expected to be key value pairs without depth.
        """
        df_cvrt = pd.DataFrame.from_dict(dict_cvrt)
        return self._dataframe_to_html(
            df_cvrt,
            precision=precision,
            header=header,
            index=index,
            sparsify=sparsify,
        )

    def _model_params_to_html(self):
        """List model attributes and values in html."""
        if SKLEARN_GTE_1_7:
            parameters = self._repr_html_()
        else:
            # TODO (sklearn > 1.6.2) remove else block
            parameters = model_attributes_to_dataframe(self)
            with pd.option_context("display.max_colwidth", 100):
                parameters = dataframe_to_html(
                    parameters,
                    precision=2,
                    header=True,
                    sparsify=False,
                )
        return parameters

    def _embed_img(self, display):
        """Embed an image or just return its instance if already embedded.

        Parameters
        ----------
        display : obj
            A Nilearn plotting object to display.

        Returns
        -------
        embed : str
            Binary image string.

        """
        if display is None:  # no image to display
            return None
        # If already embedded, simply return as is
        if isinstance(display, str):
            return display
        return figure_to_svg_base64(display.frame_axes.figure)

    def _get_body_template(self, estimator_type: str):
        """Return body template for this estimator depending on the specified
        `estimator_type` and `_template_name` attributes.
        """
        env = return_jinja_env()

        body_tpl_path = f"html/{estimator_type}/{self._template_name}"
        return env.get_template(body_tpl_path)

    def _get_partial_template(
        self, estimator_type: str, tpl_name: str, is_common: bool = False
    ):
        """Return a partial template for the specified `_estimator_type`.
        If `is_common=True`, the template is not searched in estimator's
        template directory but common `partials` directory.
        """
        env = return_jinja_env()
        loc = f"/{estimator_type}" if not is_common else ""
        return env.get_template(f"html{loc}/partials/{tpl_name}.jinja")

    def _assemble_report(self) -> HTMLReport:
        """Assemble report head and body acquiring body template corresponding
        to estimator type and populating it with report data.
        """
        page_title = self._report_content.get(
            "page_title", self.__class__.__name__
        )

        if self._report_content["engine"] == "brainsprite":
            self._set_brainsprite_data()

        estimator_type = self._report_content.get("estimator_type", "")
        body_tpl = self._get_body_template(estimator_type)

        body = body_tpl.render(**self._report_content)

        html_report = assemble_report(body, page_title)

        return html_report

    def _set_brainsprite_data(self):
        if self._has_report_data():
            report_content = self._report_content

            with (OTHER_JS / "jquery.min.js").open("r") as f:
                report_content["js_query_code"] = f.read()
            with (OTHER_JS / "brainsprite.min.js").open("r") as f:
                report_content["brainsprite_code"] = f.read()

            report_content["bg_base64"] = self._reporting_data["bg_base64"]
            report_content["cm_base64"] = self._reporting_data["cm_base64"]
            report_content["params"] = self._reporting_data["params"]
            report_content["stat_map_base64"] = self._reporting_data[
                "stat_map_base64"
            ]

    def generate_report(self, **kwargs: object) -> HTMLReport:
        """Generate an HTML report for this estimator.

        This method should be implemented in classes which inherit from
        `ReportMixin`.

        Parameters
        ----------
        kwargs : :obj:`dict` [ :obj:`str` , Any]
            Dictionary of extra key-words arguments necessary for report
            generation.

        Returns
        -------
        report : `nilearn.reporting.HTMLReport`
            HTML report for the masker.
        """
        raise NotImplementedError()
