from numpy import float64, ndarray

def _div(v: ndarray) -> ndarray: ...
def _div_id(grad: ndarray, l1_ratio: float = ...) -> ndarray: ...
def _gradient(w: ndarray) -> ndarray: ...
def _gradient_id(img: ndarray, l1_ratio: float = ...) -> ndarray: ...
def _logistic(X: ndarray, y: ndarray, w: ndarray) -> float64: ...
def _logistic_loss_grad(X: ndarray, y: ndarray, w: ndarray) -> ndarray: ...
def _logistic_loss_lipschitz_constant(X: ndarray) -> float64: ...
def _sigmoid(t: ndarray, copy: bool = ...) -> ndarray: ...
def _squared_loss(
    X: ndarray,
    y: ndarray,
    w: ndarray,
    compute_energy: bool = ...,
    compute_grad: bool = ...,
) -> float64 | ndarray: ...
def _tv_l1_from_gradient(spatial_grad: ndarray) -> float64: ...
def spectral_norm_squared(X: ndarray) -> float64: ...
