---
# Allows anyone to self-assign an issue automatically by commenting the word `take` on any issue.
#
# .. seealso::
#
#   Adapted from `Scikit-learn <https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/assign.yml>`_.
#
###
name: Assign
on:
    issue_comment:
        types: created

permissions: {}

jobs:
    one:
        permissions:
            issues: write
        runs-on: ubuntu-latest
        if: >-
            (github.event.comment.body == 'take' ||
             github.event.comment.body == 'Take')
            && !github.event.issue.assignee
        steps:
        -   name: Assign issue
            run: |
                echo "Assigning issue ${{ github.event.issue.number }} to ${GITHUB_EVENT_COMMENT_USER_LOGIN}"
                curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${GITHUB_EVENT_COMMENT_USER_LOGIN}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
                curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X "DELETE" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/help%20wanted
            env:
                GITHUB_EVENT_COMMENT_USER_LOGIN: ${{ github.event.comment.user.login }}
