---
name: test

on:
    push:
        branches:
        -   main
    pull_request:
        branches:
        -   '*'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Force to use color
env:
    FORCE_COLOR: true

jobs:

    test_js:

        name: Test HTML output
        # - run js test with browser coverage
        #   - run python examples to generate html required by javascript tests
        # - upload coverage as artifacts

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v6

        -   uses: actions/setup-node@v6
            with:
                node-version: 18

        -   name: Install the latest version of uv
            uses: astral-sh/setup-uv@v7
            with:
                python-version: '3.10'

        -   name: Install tox
            run: uv tool install tox --with=tox-uv --with=tox-gh-actions

        -   name: Run test on html output
            run: tox run -e test_html

        -   name: Upload reference, new and diff images from test
            if: success() || failure()
            uses: actions/upload-artifact@v6
            with:
                name: image
                path: tests/js/*.png
