---
name: test doc

on:
    pull_request:
        branches:
        -   '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test_doc:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout nilearn
            uses: actions/checkout@v4
        -   name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12
        -   name: Install
            run: python -m pip install .[plotting]
        -   name: Run problematic example
            run: python examples/01_plotting/plot_3d_map_to_surface_projection.py
